[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts/'
]

# Compiler settings
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200

# RPC endpoints
[rpc_endpoints]
monad = "https://rpc.monad.xyz"
